### ISSUE TITLE
It's coming.

### ISSUE THREAD

**Issue by lw** [cosmiclabsio/echo#15]
![It's a Drake GIF.](https://cloud.githubusercontent.com/assets/11558805/9389402/d28c6460-4762-11e5-8c56-842319b6e55f.gif)

**Comment by istx25** [comment]
I would appreciate it if you grew up a little bit.

**Comment by lw** [comment]
![image](https://cloud.githubusercontent.com/assets/11558805/9425571/e1b8b474-490c-11e5-8699-db8d21ed9beb.jpeg)

**Comment by trommel** [comment]
I'm coming.

**Comment by lw** [comment]
yasssss zaddy @trommel
