### ISSUE TITLE
-

### ISSUE THREAD

**Issue by citrusui** [cosmiclabsio/echo#16]

**Comment by lw** [comment]
i love you.

**Comment by istx25** [comment]
@citrusui: If you do not think that Echo is useful, **please** feel free to not use it. We built Echo to learn more about UIKit animations and custom contextual menus. Echo is no longer an active project that @damonjones and I work on, but developers like @tilomba have taken on small features to learn more about Swift and iOS development.

The "https" in the repository website URL was an oversight and I appreciate that you informed us of this, but either way the Echo site is going to be taken down sometime during the week (as you are correct - we no longer need it with the project going inactive). We are currently in the process of redesigning our branding and website which should be up in a few weeks.

I do not think that it is very mature or professional to degrade somebody's work. If you do not like what we do, please feel free to leave us and our projects alone.

**Comment by rubinovitz** [comment]
@citrusui If you're going to put "Github User" in your Twitter bio, at least try not to be a terrible one.

**Comment by audun-** [comment]
@citrusui saying shit like this is what ends up with your awful personality on display on tech forums. You seem like a genuinely shit person, and judging from your profile not much of a programmer either

**Comment by citrusui** [comment]
@audun- it's only Douglas that I don't like :). He has an awful attitude on Twitter and GitHub and whatnot. I'm ashamed he left school just to do the things he does. Self-centered prick.
![image](https://cloud.githubusercontent.com/assets/9056756/9475541/4afe3722-4b35-11e5-843a-4f5f7c618a67.gif)

**Comment by istx25** [comment]
@citrusui: I don't even know you. You are one of @lw's or @trommel's (previously @probablyjosh) friends. You don't even follow me on Twitter, nor have I seen you in any threads with my peers.

**Comment by istx25** [comment]
@citrusui: It's not your place to be "ashamed" about my education status. I may as well be a "self-centered prick", but you are not any better by disrespecting other peoples work.

**Comment by lw** [comment]
https://vine.co/v/MIJJ75vpFJJ

**Comment by rubinovitz** [comment]
You're being reported to Github. Maybe stop while you're ahead.

On Tue, Aug 25, 2015 at 2:55 PM, Douglas Bumby <notifications@github.com>
wrote:

> Reopened #16 <https://github.com/cosmiclabsio/echo/issues/16>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cosmiclabsio/echo/issues/16#event-392022383>.
>



-- 
Jennifer Rubinovitz
